


function datasum = divideStdWithMean(datasum)
	
	datasum.apMaxVRealStdapMaxVRealQuot=datasum.apMaxVRealStd/datasum.apMaxVReal;
	datasum.thresholdVRealStdthresholdVRealQuot=datasum.thresholdVRealStd/datasum.thresholdVReal;
	datasum.apEndVStdapEndVQuot=datasum.apEndVStd/datasum.apEndV;
	datasum.threshold5VRealStdthreshold5VRealQuot=datasum.threshold5VRealStd/datasum.threshold5VReal;
	datasum.apEnd5VStdapEnd5VQuot=datasum.apEnd5VStd/datasum.apEnd5V;
	datasum.halfWidhtVStdhalfWidhtVQuot=datasum.halfWidhtVStd/datasum.halfWidhtV;
	datasum.dvMaxVRealStddvMaxVRealQuot=datasum.dvMaxVRealStd/datasum.dvMaxVReal;
	datasum.dvMinVRealStddvMinVRealQuot=datasum.dvMinVRealStd/datasum.dvMinVReal;
	datasum.ahpVStdahpVQuot=datasum.ahpVStd/datasum.ahpV;
	
	datasum.apMaxVRealV0DiffStdapMaxVRealV0DiffQuot=datasum.apMaxVRealV0DiffStd/datasum.apMaxVRealV0Diff;
	datasum.thresholdVRealV0DiffStdthresholdVRealV0DiffQuot=datasum.thresholdVRealV0DiffStd/datasum.thresholdVRealV0Diff;
	datasum.apEndVV0DiffStdapEndVV0DiffQuot=datasum.apEndVV0DiffStd/datasum.apEndVV0Diff;
	datasum.threshold5VRealV0DiffStdthreshold5VRealV0DiffQuot=datasum.threshold5VRealV0DiffStd/datasum.threshold5VRealV0Diff;
	datasum.apEnd5VV0DiffStdapEnd5VV0DiffQuot=datasum.apEnd5VV0DiffStd/datasum.apEnd5VV0Diff;
	datasum.halfWidhtVV0DiffStdhalfWidhtVV0DiffQuot=datasum.halfWidhtVV0DiffStd/datasum.halfWidhtVV0Diff;
	datasum.dvMaxVRealV0DiffStddvMaxVRealV0DiffQuot=datasum.dvMaxVRealV0DiffStd/datasum.dvMaxVRealV0Diff;
	datasum.dvMinVRealV0DiffStddvMinVRealV0DiffQuot=datasum.dvMinVRealV0DiffStd/datasum.dvMinVRealV0Diff;
	datasum.ahpVV0DiffStdahpVV0DiffQuot=datasum.ahpVV0DiffStd/datasum.ahpVV0Diff;
	
	datasum.apMaxVRealthresholdVRealQuotStdapMaxVRealthresholdVRealQuotQuot=datasum.apMaxVRealthresholdVRealQuotStd/datasum.apMaxVRealthresholdVRealQuot;
	datasum.apMaxVRealapEndVQuotStdapMaxVRealapEndVQuotQuot=datasum.apMaxVRealapEndVQuotStd/datasum.apMaxVRealapEndVQuot;
	datasum.apMaxVRealhalfWidhtVQuotStdapMaxVRealhalfWidhtVQuotQuot=datasum.apMaxVRealhalfWidhtVQuotStd/datasum.apMaxVRealhalfWidhtVQuot;
	datasum.apMaxVRealdvMaxVRealQuotStdapMaxVRealdvMaxVRealQuotQuot=datasum.apMaxVRealdvMaxVRealQuotStd/datasum.apMaxVRealdvMaxVRealQuot;
	datasum.apMaxVRealdvMinVRealQuotStdapMaxVRealdvMinVRealQuotQuot=datasum.apMaxVRealdvMinVRealQuotStd/datasum.apMaxVRealdvMinVRealQuot;
	datasum.apMaxVRealahpVQuotStdapMaxVRealahpVQuotQuot=datasum.apMaxVRealahpVQuotStd/datasum.apMaxVRealahpVQuot;
	datasum.thresholdVRealapEndVQuotStdthresholdVRealapEndVQuotQuot=datasum.thresholdVRealapEndVQuotStd/datasum.thresholdVRealapEndVQuot;
	datasum.thresholdVRealhalfWidhtVQuotStdthresholdVRealhalfWidhtVQuotQuot=datasum.thresholdVRealhalfWidhtVQuotStd/datasum.thresholdVRealhalfWidhtVQuot;
	datasum.thresholdVRealdvMaxVRealQuotStdthresholdVRealdvMaxVRealQuotQuot=datasum.thresholdVRealdvMaxVRealQuotStd/datasum.thresholdVRealdvMaxVRealQuot;
	datasum.thresholdVRealdvMinVRealQuotStdthresholdVRealdvMinVRealQuotQuot=datasum.thresholdVRealdvMinVRealQuotStd/datasum.thresholdVRealdvMinVRealQuot;
	datasum.thresholdVRealahpVQuotStdthresholdVRealahpVQuotQuot=datasum.thresholdVRealahpVQuotStd/datasum.thresholdVRealahpVQuot;
	datasum.apEndVhalfWidhtVQuotStdapEndVhalfWidhtVQuotQuot=datasum.apEndVhalfWidhtVQuotStd/datasum.apEndVhalfWidhtVQuot;
	datasum.apEndVdvMaxVRealQuotStdapEndVdvMaxVRealQuotQuot=datasum.apEndVdvMaxVRealQuotStd/datasum.apEndVdvMaxVRealQuot;
	datasum.apEndVdvMinVRealQuotStdapEndVdvMinVRealQuotQuot=datasum.apEndVdvMinVRealQuotStd/datasum.apEndVdvMinVRealQuot;
	datasum.apEndVahpVQuotStdapEndVahpVQuotQuot=datasum.apEndVahpVQuotStd/datasum.apEndVahpVQuot;
	datasum.threshold5VRealapMaxVRealQuotStdthreshold5VRealapMaxVRealQuotQuot=datasum.threshold5VRealapMaxVRealQuotStd/datasum.threshold5VRealapMaxVRealQuot;
	datasum.threshold5VRealthresholdVRealQuotStdthreshold5VRealthresholdVRealQuotQuot=datasum.threshold5VRealthresholdVRealQuotStd/datasum.threshold5VRealthresholdVRealQuot;
	datasum.threshold5VRealapEndVQuotStdthreshold5VRealapEndVQuotQuot=datasum.threshold5VRealapEndVQuotStd/datasum.threshold5VRealapEndVQuot;
	datasum.threshold5VRealhalfWidhtVQuotStdthreshold5VRealhalfWidhtVQuotQuot=datasum.threshold5VRealhalfWidhtVQuotStd/datasum.threshold5VRealhalfWidhtVQuot;
	datasum.threshold5VRealdvMaxVRealQuotStdthreshold5VRealdvMaxVRealQuotQuot=datasum.threshold5VRealdvMaxVRealQuotStd/datasum.threshold5VRealdvMaxVRealQuot;
	datasum.threshold5VRealdvMinVRealQuotStdthreshold5VRealdvMinVRealQuotQuot=datasum.threshold5VRealdvMinVRealQuotStd/datasum.threshold5VRealdvMinVRealQuot;
	datasum.threshold5VRealahpVQuotStdthreshold5VRealahpVQuotQuot=datasum.threshold5VRealahpVQuotStd/datasum.threshold5VRealahpVQuot;
	datasum.apEnd5VapMaxVRealQuotStdapEnd5VapMaxVRealQuotQuot=datasum.apEnd5VapMaxVRealQuotStd/datasum.apEnd5VapMaxVRealQuot;
	datasum.apEnd5VthresholdVRealQuotStdapEnd5VthresholdVRealQuotQuot=datasum.apEnd5VthresholdVRealQuotStd/datasum.apEnd5VthresholdVRealQuot;
	if datasum.apEnd5VapEndVQuot==0
		datasum.apEnd5VapEndVQuotStdapEnd5VapEndVQuotQuot=NaN;
	else
		datasum.apEnd5VapEndVQuotStdapEnd5VapEndVQuotQuot=datasum.apEnd5VapEndVQuotStd/datasum.apEnd5VapEndVQuot;
	end
	datasum.apEnd5VhalfWidhtVQuotStdapEnd5VhalfWidhtVQuotQuot=datasum.apEnd5VhalfWidhtVQuotStd/datasum.apEnd5VhalfWidhtVQuot;
	datasum.apEnd5VdvMaxVRealQuotStdapEnd5VdvMaxVRealQuotQuot=datasum.apEnd5VdvMaxVRealQuotStd/datasum.apEnd5VdvMaxVRealQuot;
	datasum.apEnd5VdvMinVRealQuotStdapEnd5VdvMinVRealQuotQuot=datasum.apEnd5VdvMinVRealQuotStd/datasum.apEnd5VdvMinVRealQuot;
	datasum.apEnd5VahpVQuotStdapEnd5VahpVQuotQuot=datasum.apEnd5VahpVQuotStd/datasum.apEnd5VahpVQuot;
	datasum.halfWidhtVdvMaxVRealQuotStdhalfWidhtVdvMaxVRealQuotQuot=datasum.halfWidhtVdvMaxVRealQuotStd/datasum.halfWidhtVdvMaxVRealQuot;
	datasum.halfWidhtVdvMinVRealQuotStdhalfWidhtVdvMinVRealQuotQuot=datasum.halfWidhtVdvMinVRealQuotStd/datasum.halfWidhtVdvMinVRealQuot;
	datasum.halfWidhtVahpVQuotStdhalfWidhtVahpVQuotQuot=datasum.halfWidhtVahpVQuotStd/datasum.halfWidhtVahpVQuot;
	datasum.dvMaxVRealdvMinVRealQuotStddvMaxVRealdvMinVRealQuotQuot=datasum.dvMaxVRealdvMinVRealQuotStd/datasum.dvMaxVRealdvMinVRealQuot;
	datasum.dvMaxVRealahpVQuotStddvMaxVRealahpVQuotQuot=datasum.dvMaxVRealahpVQuotStd/datasum.dvMaxVRealahpVQuot;
	datasum.dvMinVRealahpVQuotStddvMinVRealahpVQuotQuot=datasum.dvMinVRealahpVQuotStd/datasum.dvMinVRealahpVQuot;
	
	datasum.threshold5apMaxDiffStdthreshold5apMaxDiffQuot=datasum.threshold5apMaxDiffStd/datasum.threshold5apMaxDiff;
	if datasum.threshold5thresholdDiff==0
		datasum.threshold5thresholdDiffStdthreshold5thresholdDiffQuot=NaN;
	else
		datasum.threshold5thresholdDiffStdthreshold5thresholdDiffQuot=datasum.threshold5thresholdDiffStd/datasum.threshold5thresholdDiff;
	end
	datasum.threshold5apEndDiffStdthreshold5apEndDiffQuot=datasum.threshold5apEndDiffStd/datasum.threshold5apEndDiff;
	datasum.threshold5halfWidthStartDiffStdthreshold5halfWidthStartDiffQuot=datasum.threshold5halfWidthStartDiffStd/datasum.threshold5halfWidthStartDiff;
	datasum.threshold5halfWidthEndDiffStdthreshold5halfWidthEndDiffQuot=datasum.threshold5halfWidthEndDiffStd/datasum.threshold5halfWidthEndDiff;
	datasum.threshold5dvMaxDiffStdthreshold5dvMaxDiffQuot=datasum.threshold5dvMaxDiffStd/datasum.threshold5dvMaxDiff;
	datasum.threshold5dvMinDiffStdthreshold5dvMinDiffQuot=datasum.threshold5dvMinDiffStd/datasum.threshold5dvMinDiff;
	datasum.threshold5ahpDiffStdthreshold5ahpDiffQuot=datasum.threshold5ahpDiffStd/datasum.threshold5ahpDiff;
	datasum.apEnd5apMaxDiffStdapEnd5apMaxDiffQuot=datasum.apEnd5apMaxDiffStd/datasum.apEnd5apMaxDiff;
	datasum.apEnd5threshold5DiffStdapEnd5threshold5DiffQuot=datasum.apEnd5threshold5DiffStd/datasum.apEnd5threshold5Diff;
	datasum.apEnd5thresholdDiffStdapEnd5thresholdDiffQuot=datasum.apEnd5thresholdDiffStd/datasum.apEnd5thresholdDiff;
	if datasum.apEnd5apEndDiff==0
		datasum.apEnd5apEndDiffStdapEnd5apEndDiffQuot=NaN;
	else
		datasum.apEnd5apEndDiffStdapEnd5apEndDiffQuot=datasum.apEnd5apEndDiffStd/datasum.apEnd5apEndDiff;
	end
	datasum.apEnd5halfWidthStartDiffStdapEnd5halfWidthStartDiffQuot=datasum.apEnd5halfWidthStartDiffStd/datasum.apEnd5halfWidthStartDiff;
	datasum.apEnd5halfWidthEndDiffStdapEnd5halfWidthEndDiffQuot=datasum.apEnd5halfWidthEndDiffStd/datasum.apEnd5halfWidthEndDiff;
	datasum.apEnd5dvMaxDiffStdapEnd5dvMaxDiffQuot=datasum.apEnd5dvMaxDiffStd/datasum.apEnd5dvMaxDiff;
	datasum.apEnd5dvMinDiffStdapEnd5dvMinDiffQuot=datasum.apEnd5dvMinDiffStd/datasum.apEnd5dvMinDiff;
	datasum.apEnd5ahpDiffStdapEnd5ahpDiffQuot=datasum.apEnd5ahpDiffStd/datasum.apEnd5ahpDiff;
	datasum.apMaxthresholdDiffStdapMaxthresholdDiffQuot=datasum.apMaxthresholdDiffStd/datasum.apMaxthresholdDiff;
	datasum.apMaxapEndDiffStdapMaxapEndDiffQuot=datasum.apMaxapEndDiffStd/datasum.apMaxapEndDiff;
	datasum.apMaxhalfWidthStartDiffStdapMaxhalfWidthStartDiffQuot=datasum.apMaxhalfWidthStartDiffStd/datasum.apMaxhalfWidthStartDiff;
	datasum.apMaxhalfWidthEndDiffStdapMaxhalfWidthEndDiffQuot=datasum.apMaxhalfWidthEndDiffStd/datasum.apMaxhalfWidthEndDiff;
	datasum.apMaxdvMaxDiffStdapMaxdvMaxDiffQuot=datasum.apMaxdvMaxDiffStd/datasum.apMaxdvMaxDiff;
	datasum.apMaxdvMinDiffStdapMaxdvMinDiffQuot=datasum.apMaxdvMinDiffStd/datasum.apMaxdvMinDiff;
	datasum.apMaxahpDiffStdapMaxahpDiffQuot=datasum.apMaxahpDiffStd/datasum.apMaxahpDiff;
	datasum.thresholdapEndDiffStdthresholdapEndDiffQuot=datasum.thresholdapEndDiffStd/datasum.thresholdapEndDiff;
	datasum.thresholdhalfWidthStartDiffStdthresholdhalfWidthStartDiffQuot=datasum.thresholdhalfWidthStartDiffStd/datasum.thresholdhalfWidthStartDiff;
	datasum.thresholdhalfWidthEndDiffStdthresholdhalfWidthEndDiffQuot=datasum.thresholdhalfWidthEndDiffStd/datasum.thresholdhalfWidthEndDiff;
	datasum.thresholddvMaxDiffStdthresholddvMaxDiffQuot=datasum.thresholddvMaxDiffStd/datasum.thresholddvMaxDiff;
	datasum.thresholddvMinDiffStdthresholddvMinDiffQuot=datasum.thresholddvMinDiffStd/datasum.thresholddvMinDiff;
	datasum.thresholdahpDiffStdthresholdahpDiffQuot=datasum.thresholdahpDiffStd/datasum.thresholdahpDiff;
	datasum.apEndhalfWidthStartDiffStdapEndhalfWidthStartDiffQuot=datasum.apEndhalfWidthStartDiffStd/datasum.apEndhalfWidthStartDiff;
	datasum.apEndhalfWidthEndDiffStdapEndhalfWidthEndDiffQuot=datasum.apEndhalfWidthEndDiffStd/datasum.apEndhalfWidthEndDiff;
	datasum.apEnddvMaxDiffStdapEnddvMaxDiffQuot=datasum.apEnddvMaxDiffStd/datasum.apEnddvMaxDiff;
	datasum.apEnddvMinDiffStdapEnddvMinDiffQuot=datasum.apEnddvMinDiffStd/datasum.apEnddvMinDiff;
	datasum.apEndahpDiffStdapEndahpDiffQuot=datasum.apEndahpDiffStd/datasum.apEndahpDiff;
	datasum.halfWidthStarthalfWidthEndDiffStdhalfWidthStarthalfWidthEndDiffQuot=datasum.halfWidthStarthalfWidthEndDiffStd/datasum.halfWidthStarthalfWidthEndDiff;
	datasum.halfWidthStartdvMaxDiffStdhalfWidthStartdvMaxDiffQuot=datasum.halfWidthStartdvMaxDiffStd/datasum.halfWidthStartdvMaxDiff;
	datasum.halfWidthStartdvMinDiffStdhalfWidthStartdvMinDiffQuot=datasum.halfWidthStartdvMinDiffStd/datasum.halfWidthStartdvMinDiff;
	datasum.halfWidthStartahpDiffStdhalfWidthStartahpDiffQuot=datasum.halfWidthStartahpDiffStd/datasum.halfWidthStartahpDiff;
	datasum.halfWidthEnddvMaxDiffStdhalfWidthEnddvMaxDiffQuot=datasum.halfWidthEnddvMaxDiffStd/datasum.halfWidthEnddvMaxDiff;
	datasum.halfWidthEnddvMinDiffStdhalfWidthEnddvMinDiffQuot=datasum.halfWidthEnddvMinDiffStd/datasum.halfWidthEnddvMinDiff;
	datasum.halfWidthEndahpDiffStdhalfWidthEndahpDiffQuot=datasum.halfWidthEndahpDiffStd/datasum.halfWidthEndahpDiff;
	datasum.dvMaxdvMinDiffStddvMaxdvMinDiffQuot=datasum.dvMaxdvMinDiffStd/datasum.dvMaxdvMinDiff;
	datasum.dvMaxahpDiffStddvMaxahpDiffQuot=datasum.dvMaxahpDiffStd/datasum.dvMaxahpDiff;
	datasum.dvMinahpDiffStddvMinahpDiffQuot=datasum.dvMinahpDiffStd/datasum.dvMinahpDiff;
	

end
