function choiceStruct = choosedialog

    d = figure('Position', [100,100,300,200],  'Name','Draw new line');
    movegui(d, 'center');
    
%     txt{1} = uicontrol(d,...
%            'Style','text',...,
%            'HorizontalAlignment','left',...
%            'Position',[10 170 100 20],...
%            'String','Choose orientation');
% 
%     txt{2} = uicontrol(d, ...
%            'Style','text',...
%            'HorizontalAlignment','left',...
%            'Position',[10 120 100 20],...
%            'String','Value');                     
       
    bg = uibuttongroup(d, 'Visible', 'on',...
        'Position', [20,150, 200, 30],...
        'Title', 'Orientation');
        
       
    r{1} = uicontrol(bg,'Style',...
                  'radio',...
                  'Position', [0, 10, 100, 20],...
                  'String','Horizontal',...
                  'HandleVisibility','off');
              
    r{2} = uicontrol(bg,'Style','radio',...
                  'Position', [0, 10, 100, 20],...
                  'String','Vertical',...
                  'HandleVisibility','off');       
              
    inputBox = uicontrol(d,...
           'Style','edit',...
           'Position',[20 90 100 25]);
    
    btn{1} = uicontrol('Parent',d,...
           'Position',[10 60 70 25],...
           'String','OK',...
           'Callback','uiresume(gcf)');       
       
    btn{2} = uicontrol('Parent',d,...
           'Position',[80 60 70 25],...
           'String','Close',...
           'Callback','delete(gcf)');
  
       
    % Wait for d to close before running to completion
    uiwait(d);

    
    choiceStruct.value = get(inputBox, 'String');
    
end